<?php
namespace Model;


class OhlasyCtenaru{
    
    const IMAGES = 'public/images/';
    
    private $odpovedi = [
        'vystupDotazniku' => 'Ohlasy na publikaci Plav! čítají několik set odpovědí napříč republikou, které s každým vydáním přibývají. Medián hodnocení je 8 z 10 možných bodů (hodnotili studenti/absolventi, učitelé, výchovní poradci, rodiče a ředitelé škol). Děkujeme všem, odpovědi nám pomáhají publikaci v příštím vydání vylepšit!', 
        'dotaznik' => 'Těšíme se i na Vaši odpověď. Klikněte prosím na <a class="textovy-odkaz" href="https://goo.gl/forms/vwBs11LGtwQKkEUo2" target="blank">DOTAZNÍK</a>',
        'sectionGraf' => [
            'nadpis' => 'Kdo odpovídal',
            'odkazAttributes' => ['href' => self::IMAGES.'dotaznik2.jpg','class' => 'ui large image', 'target' => 'blank'],
            'imgAttributes' => ['src' => self::IMAGES.'dotaznik2.jpg', 'alt' => 'graf vyhodnocení dotazníku'],
            'odkazText' => 'Zvětšit graf' 
        ],
        'sectionOdpovedi' => [
            'nadpis' => 'Odpovědi bez cenzury',
            'dataOdpovedi' => [
                    [
                    'idOtazky'=>'1',
                    'otazka' => 'Jaké využití podle Vás publikace Plav má?', 
                    'progressOdpovedi' => [
                        [
                            'progressOdpovediNazev' => 'Informativní',
                            'progressOdpovediAttributes' =>  ['data-percent' => '41']
                        ],
                        [
                            'progressOdpovediNazev' => 'Pro absolventy SŠ',
                            'progressOdpovediAttributes' =>  ['data-percent' => '23']
                        ],
                        [
                            'progressOdpovediNazev' => 'Praktické rady do života',
                            'progressOdpovediAttributes' =>  ['data-percent' => '14']
                        ]
                    ],
                    'topDeset' => [
                        'K přípravě na vstup do pracovního života, k přípravě na Závěrečné zkoušky u učebních oborů - Otázky ze světa práce.',
                        'dává velmi dobrý návod k tomu, aby člověk porozuměl sám sobě a vhodnými metodami našel povolání a uplatnění v životě',
                        'Rady jak porozumět sám sobě, vybrat si práci která baví a dává smysl. Užitečné návody jak se ucházet o místo a obstát. První krůčky v zaměstnání. Všechny informace pohromadě. Je to praktická příručka užitečná pro všechny, zejména absolventy, kteří o svém životě teprve rozhodují.',
                        'Je vhodná pro lidi kteří nemají představu o tom jak se uvést v práci, jak získat práci a jak v ní fungovat.',
                        'Získání počáteční gramotnosti pro začátek pracovní kariéry.',
                        'Jako seznámení s okolním světem v rozumné formě. Žáci si brožury pročetli a komentovali způsobem jim vlastním.',
                        'po maturitě bych se na ni určitě rád podíval, abych věděl co dál',
                        'čerpání aktuálních poznatků utříděných na jednom místě',
                        'pro budoucí práci',
                        'Orientace na trhu práce',
                    ],
                    'dalsiOdpovedi' => [
                        'žáci se lépe orientují v praktických záležitostech',
                        'Využití do života.',
                        'Ve škole i v životě',
                        'v životě a v ekonomice', 
                        'Připravit nás na reálný život',
                        'Lze se s ní připravit na závěrečné zkoušky',
                        'jak delat veci v realném životě',
                        'Mohu se podle ní vzdělávat a je tam mnoho poznatků',
                        'nevim je to kničemu ',
                        'Využití do budoucna',
                        'Publikace PLAV je naučná kniha,která nám pomůže s různými zařizováním z ekonomiky.Pomůže nám začátečníkům s úřady,prací atd..',
                        'aby studenti věděli co je tak nějak čeká',
                        'Má naučné využití v životě z ekonomiky',
                        'naučí žáky rady do života ',
                        'Publikace PLAV má dobré využití na přípravu do života práce,.',
                        'nema ',
                        'Provází nás ekonomickým světem',
                        'při výuce',
                        'Informativní', 
                        'připravit studenty na život po sš',
                        'Aby absolventi nebyli ztracení v životě',
                        'Informovat studenty o tom, co by bylo dobré vědět do budoucna',
                        'pro získání práce',
                        'Má využití pro lidi, křerí neví, co dělat po dokončení vzělání.',
                        'jako poradce pro studenty',
                        'INFORMOVAT STUDENTY O ZIVOTE',
                        'pomoc ve volbě a získání zaměstnání',
                        'Informativní (informuje o průběhu životem)',
                        'publikace PLAV je dobra knížka',
                        'ma velké využití v ekonomice',
                        'Informativní (učí nás, jak vstoupit do zaměstnání, jak se o zaměstnání ucházet a jak "plout" životem, procházet životem)',
                        'pomoci pochopit začlenění se na trh práce',
                        'informativní, pomoc při vstupu do života dospělých',
                        'pro studenty, kteří si ještě nejsou jistí co se životem',
                        'informovat studenty o budoucím studiu a povolání',
                        'Urovnání si priorit',
                        'super',
                        'příprava studentů na reální život',
                        'poučné',
                        'že pomůže poradit s prací ',
                        'příprava studentů na reálný život ',
                        'Informace',
                        'hezkou',
                        'Pro přípravu k závěrečným zkouškám na SOU a pro praxi',
                        'Rychlou právní orientaci',
                        'Dobré je tam hodně o sebemotivaci a seberustu a to se mi líbí',
                        'Příprava na reálný život',
                        'jak zacházet s penězi',
                        'zadne',
                        'v ekonomice',
                        'přípravu na život',
                        'mnoha využití',
                        'Kniha má pomoct (nasměrovat) lidi, aby věděli různé věci ze světa práce (např. jaké dostanou benefity, jak se chovat na pracovním pohovoru, jak se na něj obléci,....atd)',
                        'Poznávat skutečný život.',
                        'dobrou',
                        'získání informací',
                        'Uvědomění reálného života po škole ',
                        'vyborní',
                        'Podpora a rada k práci. ',
                        'důležité rady do života pro zaměstnání',
                        'Využití publikace je především po ukončení školy, kdy student najednou přemýšlí co vůbec se životem. Dostane vysvědčení a co teď? Nějaké nápady by byly, ale jak je a vlastně i sebe realizovat? Už jen pomůcka psaní životopisu Vám dodá  trochu sebedůvěry na nějakou pěknou pozici.',
                        'Publikaci využiváme při výuce občanské nauky studijních i učebních oborů. Je vhodná pro vyučující a studenty.',
                        'ZSV, Dějepis ',
                        'informační',
                        'Orientace na trhu práce',
                    ],
                ],[
                    'idOtazky'=>'2',
                    'otazka' => 'Nejvíce mne zaujalo:',
                    'progressOdpovedi' => [
                        [
                            'progressOdpovediNazev' => 'Vzorové životopisy',
                            'progressOdpovediAttributes' =>  ['data-percent' => '35']
                        ],
                        [
                            'progressOdpovediNazev' => 'První krůčky v zaměstnání',
                            'progressOdpovediAttributes' =>  ['data-percent' => '21']
                        ],
                        [
                            'progressOdpovediNazev' => 'Příběhy ze života',
                            'progressOdpovediAttributes' =>  ['data-percent' => '18']
                        ]
                    ],
                    'topDeset' => [
                        'Zaklepat a vstoupit - Velice pěkně zpracované, užitečné informace, které žák jinde nedostane, pokud se o tématiku nezajímá VP.',
                        'Životní příběhy reálných lidí uvedené v publikaci.',
                        'psychologické úvahy; také jsou zde pěkné ilustrace',
                        'graficky přehledné zpracování publikace',
                        'Otázky a odpovědi z praxe.',
                        'Práce v zahraničí.',
                        'Kapitola "Kdo jsem a kam směřuji.", kapitoly o volbě dalšího studia a pracovní kariéry, praktické rady pro uchazeče o zaměstnání.',
                        'Zajímavé věci, které jen tak na internetu pohromadě nenajdeme.',
                        'pracovněprávní tématika, společenské chování',
                        'pozor na paragrafy - co jsem podepsal!!!!!!!',
                    ],
                    'dalsiOdpovedi' => [
                        'Z celkově dobré úrovně příručky nic zásadně nevybočuje.',
                        'vtipné obrázky',
                        'příklady z praxe',
                        'časté dotazy absolventů',
                        'postřehy učitelů i absolventů a nabídka práce ',
                        'Pracovní pohovor',
                        'forma zpracování',
                        'vše , s čím jsem se stačil seznámit',
                        'power talking, řeč těla',
                        'Vzhledem k více jak 20 leté praxi v DD, kdy s těmito údaji pracujeme průběžně a řadě odborných seminářů a kurzů, se nedá říci, že by mne něco speciálně zaujalo - zajímavé jsou všechny kapitoly',
                        'nevím',
                        'od každého něco, nejde vybrat konkrétně',
                        'Sebemotivace. Právní minimum. Příběhy reálných lidí;',
                        'všechny kapitoly',
                        'Vše',
                        'nevím, viděla jsem ji jen předběžně a moc mě nezaujala. Příliš textu',
                        'Podaná ruka, tělo mluví pravdu..',
                        'Zajímavé věci, které jen tak na internetu pohromadě nenajdeme.',
                        'Nic konkrétního ',
                        'Životní příběhy reálných lidí uvedené v publikaci.',
                        'právní minimum',
                        'příběhy reálných  lidí',
                        'zpracování',
                        'To co jsem četl.',
                        'nevím neviděl jsem to',
                        'první strana',
                        'zaměstnání v zahraničí',
                        'Obal ',
                        'zaměstnání v zahraničí',
                        'Už jen myšlenka vydat takovou publikaci - absolvent SŠ i VŠ se tak může vyvarovat spoustě chyb v reálném životě. Reálné příběhy lidí - není to jen strohá teorie.',
                        'Část, která obsahuje odpovědi na časté dotazy studentů, které nám především kladou ihned po maturitě a absolvování studia. Mohu je tak odkázat na podrobné informace v brožuře Plav!.',
                        'Právní minimum. První krůčky v zaměstnání',
                        'Příběhy reálných lidí',
                        'kapitola Příběhy reálných lidí pro inspiraci',
                        'Ucelený přehled.',
                        'první krůčky v zaměstnání',
                        'Celá příručka jako taková:-), ze všeho nejvíc se mi však líbí, že se obrací k člověku "komplexně" - tedy vnímá jen ne tu stránku materiální, ale je v ní kladen důraz na poznání sebe sama, důležitosti uvědomit si své potřeby, touhy,  zájmy, záliby a tedy důležitost přistupovat k volbě povolání s ohledem na své pocity, nejen čistě materiálně a racionálně. ',
                        'psychologické úvahy; také jsou zde pěkné ilustrace',
                        'začátky v zaměstnání',
                        'Dobrý rozsah textu',
                        'kapitola-První krůčky v zaměstnání',
                        'Reklama na mekáč, reklama na Freko (proč tam proboha jsou nahý ženy..?)',
                        'Pár příběhů reálných lidí',
                        'nevím',
                        'vše',
                        'komunikace s Úřadem práce',
                        'Pohovor',
                        'vzorový životopis ',
                        'Jak správně napsat email',
                        'Stručné věty a vzhled knihy.',
                        'vše',
                        'popis jak si vyplním životopis',
                        'Co dělat při pohovoru',
                        'Jak je to vše přehledné a k pochopení',
                        'šablona životopisu atd..',
                        'Obrázky',
                        'všechno ',
                        'většiva věcí co se tyká našich závěreček',
                        'Sebemotivace, kdo jsem a kam směřuji, jak být jiný,aby si mě všimli a vybrali...',
                        'Power talking, sebemotivace, volba zaměstnavatele',
                        'tabulka v vypsanymi vecmi ',
                        'Životopis knížka mi ukázala jak na něj',
                        'otázky u pracovního pohovoru',
                        'osobní příběhy',
                        'Asi nic, jelikož jsem o všem byla informována už dříve',
                        'formy práce',
                        'kapitola volba dalsiho studia a seberealizace',
                        'teleworking',
                        'Celkově mi to přišlo zajímavé a užitečné.',
                        'realne pribehy lidi',
                        'vysvětlení teleworkingu',
                        'Sebepoznání',
                        'Příběhy, které nám měli přiblížit danou situaci.',
                        'způsob zpracování životopisu',
                        'Jak je kniha napsaná',
                        'porozumět sám sobě ',
                        'Že v knize je spoustu odkazů na internetové stránky, které jsou podle mě velmi užitečné. Lidem to usnadní hodně práce s hledáním informací.',
                        'obrazky',
                        'všechno',
                        'ta knížka',
                        'nic konkrétního zaujala mě celá tato knížka',
                        'všechno',
                        'Kapitoly o volbě a hledání zaměstnání a přípravě na pohovory u zaměstnavatele',
                        'Právo',
                        'Sebemotivace',
                        'vše',
                        'jak správně klepat na dveře a jak se chovat při pohovoru',
                        'vše',
                        'zivotopis',
                        'obrázky',
                        'volba zaměstnavatele',
                        'sebemotivace',
                        'Vedlejší ujednání pracovní smlouvy, Účast v konkurzu ',
                        'Často kladené dotazy u přijímacích pohovorů.', 
                        'Komunikace s vedoucím',
                        'dobre zpracování informací',
                        'Příběhy reálných lidí pro inspiraci',
                        'zaklepat a vstoupit ',
                        'Porozumět sám sobě, první krůčky k zaměstnaní.',
                        'příběhy reálných lidí ',
                        'Výborné jsou dotazy absolventů.',
                        'Otázky a odpovědi z praxe.',
                        'Ilustrace ',
                        'Image a profesionální chování',
                        'Příběhy reálných lidí',
                    ]
                ],[
                    'idOtazky'=>'3',
                    'otazka' => 'Za užitečné informace považuji:',
                    'progressOdpovedi' => [
                        [
                            'progressOdpovediNazev' => 'Jak se chovat na pohovoru',
                            'progressOdpovediAttributes' =>  ['data-percent' => '31']
                        ],
                        [
                            'progressOdpovediNazev' => 'Vše',
                            'progressOdpovediAttributes' =>  ['data-percent' => '29']
                        ],
                        [
                            'progressOdpovediNazev' => 'Životopis',
                            'progressOdpovediAttributes' =>  ['data-percent' => '24']
                        ]
                    ],
                    'topDeset' => [
                        'aktualizované požadavky trhu práce',
                        'Myslím, že obsah je dobře zvolen, těžko hodnotit, co je nejdůležitější. Každý potřebuje něco jiného.',
                        'sebemotivaci, co když mě nikde nevezmou, první krůčky v zaměstnání',
                        'otázky u pracovního pohovoru, vzory dopisů',
                        'Kniha poukazuje na možnosti, ale i výhody a nevýhody zaměstnání, dále např. rady při podpisu pracovní smlouvy a nástupu do zaměstnání a jiné.',
                        'ekonomické pojmy',
                        'finanční gramotnost',
                        'Získání informací, kam po škole. Rady do života.',
                        'Rady pro začínající zaměstnance.',
                        'Je vhodná pro lidi kteří nemají představu o tom jak se uvést v práci, jak získat práci a jak v ní fungovat.',
                    ],
                    'dalsiOdpovedi' => [
                        'návod jak psát životopis, právní minimum k pracovní smlouvě, zásady slušného chování při konkurzu, vysvětlení benefitů..',
                        'především informace o o jednání se zaměstnavatelem a první krůčky v zaměstnání',
                        'praktický návod k nalezení zaměstnání ',
                        'veškeré',
                        'Pro mládež bez pozitivního vlivu vlastní rodiny mají všechny uvedené informace význam.',
                        'přípravu na pracovní pohovor',
                        'životopis',
                        'všechny',
                        'Rady do života ',
                        'jak projít střední školou',
                        'nevím',
                        'lepší rozhodování',
                        'ohledně pracovní smlouvy',
                        'Pohovor',
                        'Veškeré rady a tipy, které jsem se dozvěděla. ',
                        'Volba dalsiho studia',
                        'Rady pro začínající zaměstnance.',
                        'často kladené dotazy u pohovorů, vzor životopisu..',
                        'informace o komunikaci',
                        'co mě v reálném životě čeká',
                        'jak najdu naměstnání',
                        'o přijetí do zaměstnání',
                        'do zaměstnání ',
                        'žadné',
                        'vše',
                        'Flexibilní forma práce, právní minimum',
                        'Postup při získávání zaměstnání',
                        'adělení vrstevníků',
                        'přehledné grafy ',
                        'právní minimum',
                        'Vzory životopisu a motivačních dopisů, otázky týkajicí se zaměstnání.',
                        'témeř vše - sezname např. dalších publikací, které umožní vyhledat si literaturu ohledně správného výběru povolání, osobní příběhy, aktuální info /např. power talking), tipa a rady....mě se osobně skutečně velmi líbí',
                        'informace o základních informacíh ohledně CV a pod.',
                        'náležitosti pracovněprávního poměru',
                        'Tipy a rady ohledně zaměstnavatele, pohovorů... Výňatky ze zákona',
                        'informace týkající se přípravy na pohovor do zaměstnání',
                        'Přípravu na získání zaměstnání',
                        'právní minimum',
                        'Všechny',
                        'První krůčky v zaměstnání',
                        'přehlednné uspořádání, praktické příklady (ukázky)',
                        'všechny informace v knize',
                        'nástup do zaměstnání',
                        'Téma hledání práce, pohovor, životopis atd.',
                        'životopis,smlouvu,jak se chovat při pohovoru',
                        'Vetšinou všechno',
                        'smlouva, životopis ',
                        'Jak správně napsat životopis',
                        'presny popis situací',
                        'životopis',
                        'je tam důležite vše,co potřebuji vědět.když tomu nerozumím vyhledám to v knize a tam je to hezky vysvětlené',
                        'asi všechno',
                        'většinu toho co je v tom',
                        'Jak postupně postupovat při hledání a dosažení práce.',
                        'zivotopis',
                        'všechno',
                        'Celá knížka je užitečná',
                        'otázky u pracovního pohovoru, vzory dopisů',
                        'Jak psát životopis ',
                        'přišly mi zajímavé osobní příběhy, ostatní informace pro mě nebyly nové',
                        'Jak si najít práci a co děla v budoucnu',
                        'jak správně napsat životopis',
                        'všechno co jde',
                        'kapitola volba dalsiho studia a seberealizace',
                        'teleworking',
                        'informace o pohovoru',
                        'nevím',
                        'Zpracování jak postupně postupovat při hledání práce',
                        'rady k pohovoru',
                        'Jak se ucházet o práci',
                        'jak se máme ucházet o zaměstnání, jaké dokumenty k tomu potřebujeme',
                        'proces pracovních pohovorů',
                        'popsání, co prožívá dospívající!',
                        'volba typu dalšího studia a pracovní kariéry ',
                        'Mně osobně se líbil popis Teleworkingu.',
                        'nevim',
                        'bylo to uzitecne',
                        'hodně informací ohledně ekonomiky ',
                        'všechno',
                        'pomůže, informace ',
                        'články, které nám objasňují hodně informací ohledně ekonomiky',
                        'Většinu',
                        'Všechny ',
                        'Právní informace (mohou se měnit)',
                        'Informace které mě posunou dál k mému snu',
                        'všechno ',
                        'vše',
                        'témata',
                        'životopis jak ho vyplnit',
                        'skoro vše',
                        'vzdělaní ,které  vyuziju po dostudovani',
                        'Pracovní benefity, Dotazy u přímacího pohovoru, vzorový průvodní životopis, vzorový průvodní dopis',
                        'Tak hlavně všeobecné informace. Každý člověk musi aspon něco vědět.',
                        'vše',
                        'nevím',
                        'Určitě porozumění sám sobě ,přijde mi to užitečné, za další příprava do zaměstnání ,pro člověka co neví co může nabídnout nebo očekávat od zaměstnavatele ...i průběh pohovoru nebo uplatnění může dost lidem otevřít oči po skončení  studia...nad tím vším se dá zamyslet a postavit se k tomu ...každému to dá jen to co si z toho bude chtít vzít...je to podle mě užitečné ale je to spíše o názoru ... a o typu lidí ... myslím si že dost lidí si to alespoň přečte 
                         příběhu reálných lidí pro inspiraci',
                        'jak na životopis atd..',
                        'Od každého něco ',
                        'jak založit živnost a vše ohledně toho když jdete žádat o práci ',
                        'Vzor životopisu, možnosti pracovních pozic.',
                        'Budoucí povolání ',
                        'informace k pracovní kariéře',
                        'Např. vzor životopisu, průvodního dopisu, internet.odkazy,informace ohledně účasti v konkurzu, verbální a neverbální komunikace,právní minimum,flexibilní formy práce',
                    ]
                ],[
                    'idOtazky'=>'4',
                    'otazka' => 'Použili jste publikaci ve výuce? Pokud ano, jak?',
                    'progressOdpovedi' => [
                        [
                            'progressOdpovediNazev' => 'Ano',
                            'progressOdpovediAttributes' =>  ['data-percent' => '32']
                        ]
                    ],
                    'topDeset' => [
                        'Ano, formou prezentace z nejdůležitějších informací obsažených v publikaci',
                        'ano; čteme si některé ukázky, používáme ji i individuálně pro potřebu žáků',
                        'besedy o dalším uplatnění absolventů',
                        'ukázky dopisů, životopisu, pracovní pohovor atd.',
                        'Ano. Informace o trhu práce, uzavírání pracovního poměru, osobní pohovor uchazečů o zaměstnání apod.',
                        'V hodinách ekonomiky - umožnila mi víc se věnovat diskusi a příkladům - žáci si nemuseli psát tolik poznámek, protože měli publikaci k dispozici. Rovněž v TC Management - pyramida potřeb.',
                        'Konzultace, výklad, praktická ukázka.',
                        'dotazy na knihu, prezentované žáky.',
                        'Zatím ne ale pripravuji se na to v pristim roce, kdy budu mít treťáky',
                        'Při přípravě na slohovou práci - motivační dopis',
                    ],
                    'dalsiOdpovedi' => [
                        'Citace, odkazy',
                        'Individuální práce s jedincem v rámci Programu rozvoje osobnosti.',
                        'seznámení s obsahem',
                        'v češtině - ve slohu (životopis)',
                        'Pouze jsme si ji ukazali',
                        'ano',
                        'dobře se z toho učí na zkoužky',
                        'va výuce žáků třetích ročníků, kteří mají u závěrečné zkoušky otázky ze světa práce',
                        'Probrání celého vydání (cca 4 vyučovací hodiny)',
                        'k výkladu, zjištění aktuálních informací, příkady pro vypracování samostatných prací, referáty na téma, diskuze se žáky',
                        'dle publikace jsme setavili životopis a žádost',
                        'ano, prolistováním',
                        'předprofesní příprava',
                        'Ve výuce předmětu Občanská nauka',
                        'Ano, při přípravě na ZZ',
                        'Navrhla jsem použití učitelům českého jazyka a občanské nauky.',
                        'vzorové: strukturovaný životopis, motivační dopis, řeč těla - pohovor - mluvní cvičení',
                        'kariérové poradenství',
                        'vyhledávání informací',
                        'Konkrétně ne, ale při informční schůzce se studenty jsem z ní citovala',
                        'ano; čteme si některé ukázky, používáme ji i individuálně pro potřebu žáků',
                        'zatím jsem nepoužili ale uvažujeme o využití v ZSV',
                        'výuka tvorby životopisu, žádisti o místo',
                        'jo',
                        'v OBN - tématika Svět práce',
                        'životopis,smlouva',
                        'Ano- cetli jsme ji ',
                        'Ano při testu',
                        'Probrali jsme knihu,a vysvětlily jsme si jak jí používat ',
                        'Ve výuce jsme to nevyužili',
                        'Ano, přečetli jsme si to',
                        'pobrali jsem ji ve výuce a vysvětlili jsme si to ',
                        'četli jsme si to co jsme nechápali',
                        'Ano publikaci jsme ve výuce použili, koukli se na obsah na důležité informace co by nás čekali po škole a co by nás čekalo také u zkoušek.',
                        'Použili jsme to ve výuce, koukali jsme na důležité informace.',
                        'ukázky dopisů, životopisu, pracovní pohovor atd.',
                        'Asi bych ji spíše studentům doporučila, pokud opravdu neví kam dál.',
                        'čtení',
                        'Fackovací pomucka',
                        'ano',
                        'představovaní knihy ve škole',
                        'Příprava na závěrečné zkoušky',
                        'prohlednutí',
                        'otazky na ekonomiku',
                        'Často kladené dotazy u přijímacích pohovorů.',
                        'Pouze jsem o ní dostali informace co v ní nalezneme.',
                        'Využití má v 3. ročníku učebních a studijních oborů v rámci světa práce.',
                        'Ano, formou prezentace z nejdůležitějších informací obsažených v publikaci',
                        'Publikaci mají k dispozici žáci v knihovně a studovně školy.',
                        'použití příkladů z publikace ',
                    ]
                ]
            ]
        ]
    ];

    public function getOdpovedi(){
        return $this->odpovedi;
    }
}

